---
title: "A calliptera"
output: html_document
date: "2025-03-27"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Libraries}
require(dplyr) #for manipulation of dataframes
require(stringr) #for useful string codes
require(geomorph) #for geometric morphometric analysis
require(ape)
require(ggplot2)
require(caper)
require(MorphoRegions)
```

```{r}
vertebrae <- readland.tps('Data/Vertebrae.tps',
                              specID = c("ID"))
```

```{r Split into Multiple Species}

#Extract species names (Genus_species) note that the index will be preserved for splitting the array
specimen_names <- dimnames(vertebrae)[[3]]
species_names <- gsub("^([A-Za-z]+_[A-Za-z]+).*", "\\1", specimen_names)

#find unique Genus_species names
unique_species <- unique(species_names)

# Initialize a list to store the resulting arrays
split_arrays <- list()

# Loop over each unique species and extract the data for that species
for (species in unique_species) {
  species_indices <- which(species_names == species)
  split_arrays[[species]] <- vertebrae[, , species_indices]
}

#split the array into entries for each species

#initialize a list to store the arrays for each species
species_arrays_list <- list()

#loop over each unique species
for (species in unique_species) {
  #extract the corresponding array for each species
  species_arrays_list[[species]] <- split_arrays[[species]]
}

# Example species_arrays_list
# species_arrays_list <- list(Astatotilapia_calliptera = arr_1, Astatotilapia_another_species = arr_2, ...)

# Function to reorder an array based on version numbers in the species names
reorder_array <- function(arr, species_names) {
  # Extract version numbers from the species names
  version_numbers <- as.numeric(gsub(".*_v(\\d+)$", "\\1", species_names))
  
  # Get the order of the species based on version numbers in ascending order
  sorted_order <- order(version_numbers)
  
  # Reorder the array based on the sorted order
  reordered_arr <- arr[, , sorted_order]
  
  return(reordered_arr)
}

# Initialize a new list to store the reordered arrays
reordered_species_arrays_list <- list()

# Loop over each species in the original list
for (species in names(species_arrays_list)) {
  # Get the array for the current species
  current_arr <- species_arrays_list[[species]]
  
  # Get the species names (dimnames)
  species_names <- dimnames(current_arr)[[3]]
  
  # Reorder the current array based on the version numbers
  reordered_species_arrays_list[[species]] <- reorder_array(current_arr, species_names)
}

#individual species entries can be accessed like this:
#reordered_species_arrays_list$Astatotilapia_calliptera
```

# Astatotilapia Calliptera

```{r Procrustes Superimpostion on Vertebral Landmark Coordinates (Astatotilapia calliptera)}
#Generalized procrustes analysis to superimose raw coordinate data (A. calliptera)
astatotilapia_callipter_proc <- gpagen(reordered_species_arrays_list$A_Calliptera, Proj=TRUE, ProcD=TRUE, curves=NULL, surfaces=NULL)

#New PCA function
a_calliptera_PCA <- gm.prcomp(astatotilapia_callipter_proc$coords)
summary(a_calliptera_PCA)
plot(a_calliptera_PCA , main="Astatotilapia calliptera PCA", axis1=1, axis2=2, type="b", pch=19)
```

```{r Prepare PCA Data for MorphoRegion (Astatotilapia calliptera)}

AC_pc_scores <- as.data.frame(a_calliptera_PCA$x[,1:5]) #using PC1-PC5 as collectively explains 95.5% of variation, rest is probably noise

AC_pc_scores <- AC_pc_scores %>%
  mutate(vertebrae = as.numeric(sub(".*_v([0-9]+).*", "\\1", rownames(AC_pc_scores)))) %>%
  dplyr::select(vertebrae, everything())
rownames(AC_pc_scores) <- NULL
```

```{r Preparing Data for MorphoRegion (Astatotilapia calliptera)}
#Process PC data for MorphoRegions
astatotilapia_calliptera <- process_measurements(AC_pc_scores, pos = 1)
astatotilapia_calliptera_pco <- svdPCO(astatotilapia_calliptera, metric = 'Manhattan')

#Plot PCOs along backbone for PC1 and 2:
plot(astatotilapia_calliptera_pco, 1:5)
```

```{r Determine number of PCOs to Retain (Astatotilapia calliptera)}
#define number of PCOs to retain - just 5 since we input 5 PC axes
PCOs <- PCOselect(astatotilapia_calliptera_pco, method = "manual",
                  scores = 5)
```

```{r Testing Number of Regions in Vertebral Column (Astatotilapia calliptera)}

astatotilapia_calliptera_regionresults <- calcregions(astatotilapia_calliptera_pco, scores = PCOs, noregions = 8,
                             minvert = 2, cont = TRUE, 
                             exhaus = TRUE, cl = NULL,
                             verbose = FALSE) #we have 26 vertebrae, max number of regions is 8 (assuming 3 vertebrae per/region)
##output summary
models <- modelselect(astatotilapia_calliptera_regionresults)
supp <- modelsupport(models)
supp
```

```{r Plotting PCOs and Best Fitting Model (Astatotilapia calliptera)}
#Plot regressions for best model:
plotsegreg(astatotilapia_calliptera_pco, scores = 1:5, #plot all retained PCOs
           modelsupport = supp,
           criterion = "aic",
           model = 1) #plot best fitting model (i.e. model = 1, as determined by the BIC value)

#Plot regressions for best fitting model with the break points:
#plotsegreg(astatotilapia_calliptera_pco, scores = 1, #limit this to just PCO 1
           #bps = c(5, 8, 15, 24),
           #cont = TRUE)
```

min 2 vert
```{r}
# making a visual map
regionresults <- calcregions(astatotilapia_calliptera_pco, scores = 1:27, noregions = 6, 
                             minvert = 2, cont = TRUE, exhaus = TRUE,
                             verbose = FALSE)

bpvar <- calcBPvar(regionresults, noregions = 5,
                   pct = 0.1, criterion = "aic")
plotvertmap(astatotilapia_calliptera_pco, name = "A_calliptera",
            modelsupport = supp, criterion = "aic", model = 1)



## AIC model, min 2 vert
xy <- plotvertmap(astatotilapia_calliptera_pco, name = "A_calliptera",
            modelsupport = supp, criterion = "bic", model = 1) +
    theme(axis.title.y = element_text(vjust = 0.18)) +
    scale_y_continuous(limits = c(0, 10)) +
    scale_x_continuous(position = "bottom")

xy

tx2 <- plotvertmap(astatotilapia_calliptera_pco, name = "A_calliptera",
            bpvar = bpvar, model = 1, dropNA = TRUE) +
    theme(axis.title.y = element_text(vjust = 0.18)) +
    scale_y_continuous(limits = c(0, 10)) +
    scale_x_continuous(position = "bottom")
tx2

ggsave("Figures/Regionalisation/AC min2.jpeg", xy, width = 25, height = 15, units = "cm")
ggsave("Figures/Regionalisation/AC min2 eb.jpeg", tx2, width = 25, height = 15, units = "cm")

```

### min 3 vert

```{r}

astatotilapia_calliptera_regionresults <- calcregions(astatotilapia_calliptera_pco, scores = PCOs, noregions = 8,
                             minvert = 3, cont = TRUE, 
                             exhaus = TRUE, cl = NULL,
                             verbose = FALSE) #we have 26 vertebrae, max number of regions is 8 (assuming 3 vertebrae per/region)
##output summary
models <- modelselect(astatotilapia_calliptera_regionresults)
supp <- modelsupport(models)
```


```{r}
plotsegreg(astatotilapia_calliptera_pco, scores = 1:5, #plot all retained PCOs
           modelsupport = supp,
           criterion = "aic",
           model = 1) 
```


```{r}
# making a visual map
regionresults <- calcregions(astatotilapia_calliptera_pco, scores = 1:27, noregions = 6, 
                             minvert = 3, cont = TRUE, exhaus = TRUE,
                             verbose = FALSE)

bpvar <- calcBPvar(regionresults, noregions = 5,
                   pct = 0.1, criterion = "aic")
plotvertmap(astatotilapia_calliptera_pco, name = "A_calliptera",
            modelsupport = supp, criterion = "aic", model = 1)

## AIC model, min 3 vert
AB <- plotvertmap(astatotilapia_calliptera_pco, name = "A_calliptera",
            modelsupport = supp, criterion = "aic", model = 1) +
    theme(axis.title.y = element_text(vjust = 0.18)) +
    scale_y_continuous(limits = c(0, 10)) +
    scale_x_continuous(position = "bottom")

AB

tx2 <- plotvertmap(astatotilapia_calliptera_pco, name = "A_calliptera",
            bpvar = bpvar, model = 1, dropNA = TRUE) +
    theme(axis.title.y = element_text(vjust = 0.18)) +
    scale_y_continuous(limits = c(0, 10)) +
    scale_x_continuous(position = "bottom")
tx2

ggsave("Figures/Regionalisation/AC min3.jpeg", AB, width = 25, height = 15, units = "cm")
ggsave("Figures/Regionalisation/AC min3 eb.jpeg", tx2, width = 25, height = 15, units = "cm")
```







